Display Recode
Squagward/ChatTriggers pull request #1
Opened 2022-05-21 07:37 UTC by DalwynWasTaken

Breaking changes to Display section of ChatTriggers. I'm merging it here so it can be added later. Feel free to polish it if you feel like something is missing/wrong

2022-05-21 07:39 UTC, DalwynWasTaken commented
Not sure how to remove the Merge commit, but it shouldn't effect a thing. And changelog for Display is in the Display Recode commit

2022-05-21 14:06 UTC, Squagward requested changes

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +    private var textColor: Long = 0xFFFFFFFF
Revert these back to 0xffffffff to be consistent with the other files

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> -    @JvmOverloads
@JvmOverloads needs to stay since the index is optional.

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +    fun removeLine(line: Any) = apply {
Add a string option here

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +        this.visible = true
Remove all unneeded uses of `this`, I might have missed a couple.

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +}
Add a new line at the end and remove the empty line above.

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/DisplayHandler.kt
> +}
Same thing here, remove the new line on line 59 and add one after line 60

2022-05-21 14:06 UTC, camnwalter commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/DisplayLine.kt
> -        }
Why was dragged removed?

2022-05-21 14:06 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/DisplayLine.kt
>  }
Add a new line at the very end

2022-05-21 14:06 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +        this.lines[index] = when (line) {
Remove unneeded `this`

2022-05-21 14:06 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +        this.lines.clear()
Remove unneeded `this`

2022-05-21 14:06 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +    internal abstract fun getLoader(): ILoader
Inside `Impl.kt`, add `override fun getLoader` for JSDisplay like the other classes in there.

2022-05-21 14:09 UTC, Squagward commented
> Not sure how to remove the Merge commit, but it shouldn't effect a thing. And changelog for Display is in the Display Recode commit

I can fix the merge commit whenever I merge this in, don't worry about that.

2022-05-22 06:35 UTC, DalwynWasTaken commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/DisplayLine.kt
> -        }
It has absolutely no use other than adding a check to the dragged method. Just allow the user to define their own dragged register at this point.

2022-05-22 06:42 UTC, DalwynWasTaken commented
I don't understand the new line stuff so I based it off of what the current CT main branch looks like. And I finally understand why some properties have this and others don't. I didn't realize that until I went through to remove unnecessary this's

2022-05-22 06:48 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/DisplayLine.kt
> -        }
Ok yeah that makes sense.  Register dragged for a single DisplayLine doesn't make too much sense.

2022-05-22 06:57 UTC, Squagward requested changes

2022-05-22 06:57 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +            is String -> this.lines.find { it.getText() == line }
Remove `this`

2022-05-22 06:57 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +            is String -> lines.forEach { if (it.getText() == line) lines.remove(it) }
```suggestion
            is String -> lines.removeIf { it.getText() == line }
```

2022-05-22 07:05 UTC, Squagward commented on src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt
> +            is String -> lines.forEach { if (it.getText() == line) lines.remove(it) }
Actually, that won't do it since `getText` returns a `Text`, not a string, but still.

2022-05-22 07:19 UTC, Squagward commented
LGTM thank you 👍

2022-05-22 07:19 UTC, merged